In [4]:
class className:
    #some functions and variables
    #function-- used to  perform some certain activity
    #variable--data(memory)
        

SyntaxError: unexpected EOF while parsing (<ipython-input-4-80266120f559>, line 5)

In [5]:
def demo:
    return
test()


SyntaxError: invalid syntax (<ipython-input-5-a666fbbcd14e>, line 1)

In [8]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()

test()for the class and method


In [16]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [27]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
        
c1=Demo2(10,20)
print(c1.add(100,200))



300


In [36]:
#some inheritance

class person(object):
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
#Derived class
class employee(person):
    def isemployee(self):
        return True
    
emp=person("Anil")
print(emp.getname(),emp.isemployee())

emp1=employee("raja")
print(emp1.getname(),emp1.isemployee())

    

Anil False
raja True


In [38]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)


[1 2 3 4]


In [39]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [43]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
float64


In [41]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [42]:
#Re-shape the given array
# numpy.reshape(arrayName,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [47]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [48]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)


[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [46]:

A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=5
np.asarray(A)[3][3]=23
print(A)


[[ 1  1  1  1]
 [ 1  1  1  5]
 [ 1  1  1  1]
 [ 1  1  1 23]]


In [49]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [50]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[0])

second row: [1 2 3]


In [53]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[5.54608949 5.11484926 4.41230175 3.00074971 4.92066122 6.35027967
 6.66711803 4.89158072 4.91544911 4.68239702]
Min value= 3.0007497139552592
Max value= 6.667118033277381
Mean value= 5.050147599158125
Median value= 4.918055161575536


In [54]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [55]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [59]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [62]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
    "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
    "Mobile Number":[99,44,55,22,33,41]}

b=pd.DataFrame(dict)
print(b)


     Name           EmailID  Mobile Number
0    Anil    anil@gmail.com             99
1   Akhil   akhil@gmail.com             44
2  Dinesh  dinesh@gmail.com             55
3  Harsha  harsha@gmail.com             22
4    Ajay    ajay@gmail.com             33
5  Kranth  kranth@gmail.com             41


In [63]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  Mobile Number
01    Anil    anil@gmail.com             99
02   Akhil   akhil@gmail.com             44
03  Dinesh  dinesh@gmail.com             55
04  Harsha  harsha@gmail.com             22
05    Ajay    ajay@gmail.com             33
06  Kranth  kranth@gmail.com             41


In [ ]:
import pandas as pd
products=pd.read_csv('filename.csv')
print(products)
